services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: backend-nodejs-prisma-starter-kit-prod:latest
    container_name: app-api-prod
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: app-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
